import Sixpack

#print axioms Sixpack.root13_nonneg
#print axioms Sixpack.root13_sq
#print axioms Sixpack.root13_bounds
#print axioms Sixpack.optimum_polynomial
#print axioms Sixpack.optimum_bounds
#print axioms Sixpack.optimum_lt_outerBound
#print axioms Sixpack.coarse_cell_diameter
#print axioms Sixpack.scaledNormSq_cartesian
#print axioms Sixpack.centerEmbed_margins
#print axioms Sixpack.centerEmbed_strict
#print axioms Sixpack.strictlyInContainer_not_boundary
#print axioms Sixpack.centerEmbed_preserves_delta
#print axioms Sixpack.rotate_preserves_norm
#print axioms Sixpack.halfAngle_identity
#print axioms Sixpack.lower_bound_from_boundary_classification
#print axioms Sixpack.candidate_unit_sides
#print axioms Sixpack.candidate_vertices_contained
#print axioms Sixpack.candidate_ccw
#print axioms Sixpack.candidate_separating_edges
#print axioms Sixpack.candidate_has_boundary_vertex
#print axioms Sixpack.local_omission
#print axioms Sixpack.negative_slack_excludes_separation
#print axioms Sixpack.tube_forces_zero
#print axioms Sixpack.projection_surjective
#print axioms Sixpack.convex_container
#print axioms Sixpack.candidate_hulls_contained
#print axioms Sixpack.separated_hulls_disjoint_interiors
#print axioms Sixpack.candidate_inside_witness_edge
#print axioms Sixpack.candidate_hulls_disjoint_of_lt
#print axioms Sixpack.candidate_hulls_pairwise_disjoint
#print axioms Sixpack.candidate_feasible
#print axioms Sixpack.candidate_isPacking
#print axioms Sixpack.candidate_upper_bound
#print axioms Sixpack.arc_deletion_preserves_selection
#print axioms Sixpack.vertex_branch_preserves_selection
#print axioms Sixpack.omission_domains_preserve_uncovered_selection
#print axioms Sixpack.Quadratic13.value_add
#print axioms Sixpack.Quadratic13.value_neg
#print axioms Sixpack.Quadratic13.value_mul
#print axioms Sixpack.Quadratic13.nonnegative_iff
#print axioms Sixpack.hull_centerEmbed
#print axioms Sixpack.packing_vertices_contained
#print axioms Sixpack.packing_centerEmbed
#print axioms Sixpack.lower_bound_of_endpoint_boundary
#print axioms Sixpack.outerTriangle_sides
#print axioms Sixpack.outerTriangle_vertices_contained
#print axioms Sixpack.outerTriangle_hull_eq
#print axioms Sixpack.candidate_in_equilateral_container

#print axioms Sixpack.checkSearch_sound
#print axioms Sixpack.prototype_accepts
#print axioms Sixpack.prototype_no_selection
#print axioms Sixpack.prototype_false_closure_rejected
#print axioms Sixpack.prototype_corrupt_graph_rejected
#print axioms Sixpack.intervalAdj_conservative
#print axioms Sixpack.interval_certificate_sound
#print axioms Sixpack.interval_prototype_accepts
#print axioms Sixpack.three_unit_intervals_do_not_fit
#print axioms Sixpack.radius_estimates_force_zero
#print axioms Sixpack.radius_uniform_gap
#print axioms Sixpack.corner_fixed_centroid_rigid
#print axioms Sixpack.corner_fixed_centroid_vertices
#print axioms Sixpack.checked_radius_estimates_force_zero
#print axioms Sixpack.radius_branch_zero_accepts
#print axioms Sixpack.radius_branch_zero_estimates_force_zero
#print axioms Sixpack.radius_truncated_input_rejected

#print axioms Sixpack.Quadratic13.value_zero
#print axioms Sixpack.Quadratic13.value_one
#print axioms Sixpack.Quadratic13.value_rational
#print axioms Sixpack.Quadratic13.value_sub
#print axioms Sixpack.Quadratic13.value_sum
#print axioms Sixpack.Quadratic13.positive_iff
#print axioms Sixpack.Quadratic13.value_ite
#print axioms Sixpack.Quadratic13.value_dot
#print axioms Sixpack.checked_linear_surjective
#print axioms Sixpack.checked_linear_kernel
#print axioms Sixpack.checked_linear_decomposition
#print axioms Sixpack.checked_linear_motion
#print axioms Sixpack.exactCandidate_value
#print axioms Sixpack.exactPointSub_value
#print axioms Sixpack.exactCross_value
#print axioms Sixpack.exactCentroid_value
#print axioms Sixpack.exactProjection_value
#print axioms Sixpack.exactVertexColumn_velocity
#print axioms Sixpack.exactGradient_velocity
#print axioms Sixpack.trig_rotation_identity
#print axioms Sixpack.localVertexPath_unit_sides
#print axioms Sixpack.localVertexPath_zero
#print axioms Sixpack.localVertexPath_derivative
#print axioms Sixpack.localConstraintPath_zero
#print axioms Sixpack.point_derivative_fst
#print axioms Sixpack.point_derivative_snd
#print axioms Sixpack.localConstraintPath_derivative
#print axioms Sixpack.localConstraintPath_exact_derivative
#print axioms Sixpack.first_order_branch_zero_accepts
#print axioms Sixpack.first_order_branch_zero_geometry
#print axioms Sixpack.first_order_branch_zero_active
#print axioms Sixpack.first_order_branch_zero_basepoint
#print axioms Sixpack.first_order_branch_zero_slacks
#print axioms Sixpack.first_order_branch_zero_derivative
#print axioms Sixpack.first_order_branch_zero_motion
#print axioms Sixpack.first_order_branch_one_accepts
#print axioms Sixpack.first_order_branch_one_geometry
#print axioms Sixpack.first_order_branch_one_active
#print axioms Sixpack.first_order_branch_one_basepoint
#print axioms Sixpack.first_order_branch_one_slacks
#print axioms Sixpack.first_order_branch_one_derivative
#print axioms Sixpack.first_order_branch_one_motion
#print axioms Sixpack.first_order_branch_two_accepts
#print axioms Sixpack.first_order_branch_two_geometry
#print axioms Sixpack.first_order_branch_two_active
#print axioms Sixpack.first_order_branch_two_basepoint
#print axioms Sixpack.first_order_branch_two_slacks
#print axioms Sixpack.first_order_branch_two_derivative
#print axioms Sixpack.first_order_branch_two_motion
#print axioms Sixpack.first_order_branch_three_accepts
#print axioms Sixpack.first_order_branch_three_geometry
#print axioms Sixpack.first_order_branch_three_active
#print axioms Sixpack.first_order_branch_three_basepoint
#print axioms Sixpack.first_order_branch_three_slacks
#print axioms Sixpack.first_order_branch_three_derivative
#print axioms Sixpack.first_order_branch_three_motion
#print axioms Sixpack.first_order_branch_four_accepts
#print axioms Sixpack.first_order_branch_four_geometry
#print axioms Sixpack.first_order_branch_four_active
#print axioms Sixpack.first_order_branch_four_basepoint
#print axioms Sixpack.first_order_branch_four_slacks
#print axioms Sixpack.first_order_branch_four_derivative
#print axioms Sixpack.first_order_branch_four_motion
#print axioms Sixpack.first_order_branch_five_accepts
#print axioms Sixpack.first_order_branch_five_geometry
#print axioms Sixpack.first_order_branch_five_active
#print axioms Sixpack.first_order_branch_five_basepoint
#print axioms Sixpack.first_order_branch_five_slacks
#print axioms Sixpack.first_order_branch_five_derivative
#print axioms Sixpack.first_order_branch_five_motion
#print axioms Sixpack.first_order_branch_six_accepts
#print axioms Sixpack.first_order_branch_six_geometry
#print axioms Sixpack.first_order_branch_six_active
#print axioms Sixpack.first_order_branch_six_basepoint
#print axioms Sixpack.first_order_branch_six_slacks
#print axioms Sixpack.first_order_branch_six_derivative
#print axioms Sixpack.first_order_branch_six_motion
#print axioms Sixpack.first_order_branch_seven_accepts
#print axioms Sixpack.first_order_branch_seven_geometry
#print axioms Sixpack.first_order_branch_seven_active
#print axioms Sixpack.first_order_branch_seven_basepoint
#print axioms Sixpack.first_order_branch_seven_slacks
#print axioms Sixpack.first_order_branch_seven_derivative
#print axioms Sixpack.first_order_branch_seven_motion
#print axioms Sixpack.all_first_order_branches_accept
#print axioms Sixpack.first_order_zero_weight_rejected
#print axioms Sixpack.Quadratic13.value_absolute
#print axioms Sixpack.Quadratic13.checkLower_iff
#print axioms Sixpack.Quadratic13.checkUpper_iff
#print axioms Sixpack.checked_linear_enclosures
#print axioms Sixpack.checked_linear_slack_bound
#print axioms Sixpack.branch_zero_linear_enclosures_accept
#print axioms Sixpack.branch_zero_constraint_derivative_bound
#print axioms Sixpack.branch_zero_multiplier_lower_bounds
#print axioms Sixpack.branch_zero_inverse_absolute_bounds

#print axioms Sixpack.branch_zero_kernel_bounds_accept
#print axioms Sixpack.branch_zero_kernel_absolute_bound
