import Sixpack.EndpointRootCase715BlockerBinding.Batch0
import Sixpack.EndpointRootCase715BlockerBinding.Batch1
import Sixpack.EndpointRootCase715BlockerBinding.Batch2
import Sixpack.EndpointRootCase715BlockerBinding.Batch3
import Sixpack.EndpointRootCase715BlockerBinding.Batch4
import Sixpack.EndpointRootCase715BlockerBinding.Batch5
import Sixpack.EndpointRootCase715BlockerBinding.Batch6
import Sixpack.EndpointRootCase715BlockerBinding.Batch7
import Sixpack.EndpointRootCase715BlockerBinding.Batch8
import Sixpack.EndpointRootCase715BlockerBinding.Batch9
import Sixpack.EndpointRootCase715BlockerBinding.Batch10
import Sixpack.EndpointRootCase715BlockerBinding.Batch11
import Sixpack.EndpointRootCase715BlockerBinding.Batch12
import Sixpack.EndpointRootCase715BlockerBinding.Batch13
import Sixpack.EndpointRootCase715BlockerBinding.Batch14
import Sixpack.EndpointRootCase715BlockerBinding.Batch15
import Sixpack.EndpointRootCase715BlockerBinding.Batch16
import Sixpack.EndpointRootCase715BlockerBinding.Batch17
import Sixpack.EndpointRootCase715BlockerBinding.Batch18
import Sixpack.EndpointRootCase715BlockerBinding.Batch19
import Sixpack.EndpointRootCase715BlockerBinding.Batch20
import Sixpack.EndpointRootCase715BlockerBinding.Batch21
import Sixpack.EndpointRootCase715BlockerBinding.Batch22
import Sixpack.EndpointRootCase715BlockerBinding.Batch23
import Sixpack.EndpointRootCase715BlockerBinding.Batch24
import Sixpack.EndpointRootCase715BlockerBinding.Batch25
import Sixpack.EndpointRootCase715BlockerBinding.Batch26
import Sixpack.EndpointRootCase715BlockerBinding.Batch27
import Sixpack.EndpointRootCase715BlockerBinding.Batch28
import Sixpack.EndpointRootCase715BlockerBinding.Batch29
import Sixpack.EndpointRootCase715BlockerBinding.Batch30
import Sixpack.EndpointRootCase715BlockerBinding.Batch31
import Sixpack.EndpointRootCase715BlockerBinding.Batch32
import Sixpack.EndpointRootCase715BlockerBinding.Batch33
import Sixpack.EndpointRootCase715BlockerBinding.Batch34
import Sixpack.EndpointRootCase715BlockerBinding.Batch35
import Sixpack.EndpointRootCase715BlockerBinding.Batch36
import Sixpack.EndpointRootCase715BlockerBinding.Batch37
import Sixpack.EndpointRootCase715BlockerBinding.Batch38
import Sixpack.EndpointRootCase715BlockerBinding.Batch39
import Sixpack.EndpointRootCase715BlockerBinding.Batch40
import Sixpack.EndpointRootCase715BlockerBinding.Batch41
import Sixpack.EndpointRootCase715BlockerBinding.Batch42
import Sixpack.EndpointRootCase715BlockerBinding.Batch43
import Sixpack.EndpointRootCase715BlockerBinding.Batch44
import Sixpack.EndpointRootCase715BlockerBinding.Batch45
import Sixpack.EndpointRootCase715BlockerBinding.Batch46
import Sixpack.EndpointRootCase715BlockerBinding.Batch47
import Sixpack.EndpointRootCase715BlockerBinding.Batch48
import Sixpack.EndpointRootCase715BlockerBinding.Batch49
import Sixpack.EndpointRootCase715BlockerBinding.Batch50
import Sixpack.EndpointRootCase715BlockerBinding.Batch51
import Sixpack.EndpointRootCase715BlockerBinding.Batch52
import Sixpack.EndpointRootCase715BlockerBinding.Batch53
import Sixpack.EndpointRootCase715BlockerBinding.Batch54
import Sixpack.EndpointRootCase715BlockerBinding.Batch55
import Sixpack.EndpointRootCase715BlockerBinding.Batch56
import Sixpack.EndpointRootCase715BlockerBinding.Batch57
import Sixpack.EndpointRootCase715BlockerBinding.Batch58
import Sixpack.EndpointRootCase715BlockerBinding.Batch59
import Sixpack.EndpointRootCase715BlockerBinding.Batch60
import Sixpack.EndpointRootCase715BlockerBinding.Batch61
import Sixpack.EndpointRootCase715BlockerBinding.Batch62
import Sixpack.EndpointRootCase715BlockerBinding.Batch63
import Sixpack.EndpointRootCase715BlockerBinding.Batch64
import Sixpack.EndpointRootCase715BlockerBinding.Batch65
import Sixpack.EndpointRootCase715BlockerBinding.Batch66
import Sixpack.EndpointRootCase715BlockerBinding.Batch67
import Sixpack.EndpointRootCase715BlockerBinding.Batch68
import Sixpack.EndpointRootCase715BlockerBinding.Batch69
import Sixpack.EndpointRootCase715BlockerBinding.Batch70
import Sixpack.EndpointRootCase715BlockerBinding.Batch71
import Sixpack.EndpointRootCase715BlockerBinding.Batch72
import Sixpack.EndpointRootCase715BlockerBinding.Batch73
import Sixpack.EndpointRootCase715BlockerBinding.Batch74
import Sixpack.EndpointRootCase715BlockerBinding.Batch75
import Sixpack.EndpointRootCase715BlockerBinding.Batch76
import Sixpack.EndpointRootCase715BlockerBinding.Batch77
import Sixpack.EndpointRootCase715BlockerBinding.Batch78
import Sixpack.EndpointRootCase715BlockerBinding.Batch79
import Sixpack.EndpointRootCase715BlockerBinding.Batch80
import Sixpack.EndpointRootCase715BlockerBinding.Batch81
import Sixpack.EndpointRootCase715BlockerBinding.Batch82
import Sixpack.EndpointRootCase715BlockerBinding.Batch83
import Sixpack.EndpointRootCase715BlockerBinding.Batch84
import Sixpack.EndpointRootCase715BlockerBinding.Batch85
import Sixpack.EndpointRootCase715BlockerBinding.Batch86
import Sixpack.EndpointRootCase715BlockerBinding.Batch87
import Sixpack.EndpointRootCase715BlockerBinding.Batch88
import Sixpack.EndpointRootCase715BlockerBinding.Batch89
import Sixpack.EndpointRootCase715BlockerBinding.Batch90
import Sixpack.EndpointRootCase715BlockerBinding.Batch91
import Sixpack.EndpointRootCase715BlockerBinding.Batch92
import Sixpack.EndpointRootCase715BlockerBinding.Batch93
import Sixpack.EndpointRootCase715BlockerBinding.Batch94
import Sixpack.EndpointRootCase715BlockerBinding.Batch95
import Sixpack.EndpointRootCase715BlockerBinding.Batch96
import Sixpack.EndpointRootCase715BlockerBinding.Batch97
import Sixpack.EndpointRootCase715BlockerBinding.Batch98
import Sixpack.EndpointRootCase715BlockerBinding.Batch99
import Sixpack.EndpointRootCase715BlockerBinding.Batch100
import Sixpack.EndpointRootCase715BlockerBinding.Batch101
import Sixpack.EndpointRootCase715BlockerBinding.Batch102
import Sixpack.EndpointRootCase715BlockerBinding.Batch103
import Sixpack.EndpointRootCase715BlockerBinding.Batch104
import Sixpack.EndpointRootCase715BlockerBinding.Batch105
import Sixpack.EndpointRootCase715BlockerBinding.Batch106
import Sixpack.EndpointRootCase715BlockerBinding.Batch107
import Sixpack.EndpointRootCase715BlockerBinding.Batch108
import Sixpack.EndpointRootCase715BlockerBinding.Batch109
import Sixpack.EndpointRootCase715BlockerBinding.Batch110
import Sixpack.EndpointRootCase715BlockerBinding.Batch111
import Sixpack.EndpointRootCase715BlockerBinding.Batch112
import Sixpack.EndpointRootCase715BlockerBinding.Batch113
import Sixpack.EndpointRootCase715BlockerBinding.Batch114
import Sixpack.EndpointRootCase715BlockerBinding.Batch115
import Sixpack.EndpointRootCase715BlockerBinding.Batch116
import Sixpack.EndpointRootCase715BlockerBinding.Batch117
import Sixpack.EndpointRootCase715BlockerBinding.Batch118
import Sixpack.EndpointRootCase715BlockerBinding.Batch119
import Sixpack.EndpointRootCase715BlockerBinding.Batch120
import Sixpack.EndpointRootCase715BlockerBinding.Batch121
import Sixpack.EndpointRootCase715BlockerBinding.Batch122
import Sixpack.EndpointRootCase715BlockerBinding.Batch123
import Sixpack.EndpointRootCase715BlockerBinding.Batch124
import Sixpack.EndpointRootCase715BlockerBinding.Batch125
import Sixpack.EndpointRootCase715BlockerBinding.Batch126
import Sixpack.EndpointRootCase715BlockerBinding.Batch127
import Sixpack.EndpointRootCase715BlockerBinding.Batch128
import Sixpack.EndpointRootCase715BlockerBinding.Batch129
import Sixpack.EndpointRootCase715BlockerBinding.Batch130
import Sixpack.EndpointRootCase715BlockerBinding.Batch131
import Sixpack.EndpointRootCase715BlockerBinding.Batch132
import Sixpack.EndpointRootCase715BlockerBinding.Batch133
import Sixpack.EndpointRootCase715BlockerBinding.Batch134
import Sixpack.EndpointRootCase715BlockerBinding.Batch135
import Sixpack.EndpointRootCase715BlockerBinding.Batch136
import Sixpack.EndpointRootCase715BlockerBinding.Batch137
import Sixpack.EndpointRootCase715BlockerBinding.Batch138
import Sixpack.EndpointRootCase715BlockerBinding.Batch139
import Sixpack.EndpointRootCase715BlockerBinding.Batch140
import Sixpack.EndpointRootCase715BlockerBinding.Batch141
import Sixpack.EndpointRootCase715BlockerBinding.Batch142
import Sixpack.EndpointRootCase715BlockerBinding.Batch143
import Sixpack.EndpointRootCase715BlockerBinding.Batch144
import Sixpack.EndpointRootCase715BlockerBinding.Batch145
import Sixpack.EndpointRootCase715BlockerBinding.Batch146
import Sixpack.EndpointRootCase715BlockerBinding.Batch147
import Sixpack.EndpointRootCase715BlockerBinding.Batch148
import Sixpack.EndpointRootCase715BlockerBinding.Batch149
import Sixpack.EndpointRootCase715BlockerBinding.Batch150
import Sixpack.EndpointRootCase715BlockerBinding.Batch151
import Sixpack.EndpointRootCase715BlockerBinding.Batch152
import Sixpack.EndpointRootCase715BlockerBinding.Batch153
import Sixpack.EndpointRootCase715BlockerBinding.Batch154
import Sixpack.EndpointRootCase715BlockerBinding.Batch155
import Sixpack.EndpointRootCase715BlockerBinding.Batch156
import Sixpack.EndpointRootCase715BlockerBinding.Batch157
import Sixpack.EndpointRootCase715BlockerBinding.Batch158
import Sixpack.EndpointRootCase715BlockerBinding.Batch159
import Sixpack.EndpointRootCase715BlockerBinding.Batch160
import Sixpack.EndpointRootCase715BlockerBinding.Batch161
import Sixpack.EndpointRootCase715BlockerBinding.Batch162
import Sixpack.EndpointRootCase715BlockerBinding.Batch163
import Sixpack.EndpointRootCase715BlockerBinding.Batch164
import Sixpack.EndpointRootCase715BlockerBinding.Batch165
import Sixpack.EndpointRootCase715BlockerBinding.Batch166
import Sixpack.EndpointRootCase715BlockerBinding.Batch167
import Sixpack.EndpointRootCase715BlockerBinding.Batch168
import Sixpack.EndpointRootCase715BlockerBinding.Batch169
import Sixpack.EndpointRootCase715BlockerBinding.Batch170
import Sixpack.EndpointRootCase715BlockerBinding.Batch171
import Sixpack.EndpointRootCase715BlockerBinding.Batch172
import Sixpack.EndpointRootCase715BlockerBinding.Batch173
import Sixpack.EndpointRootCase715BlockerBinding.Batch174
import Sixpack.EndpointRootCase715BlockerBinding.Batch175
import Sixpack.EndpointRootCase715BlockerBinding.Batch176
import Sixpack.EndpointRootCase715BlockerBinding.Batch177
import Sixpack.EndpointRootCase715BlockerBinding.Batch178
import Sixpack.EndpointRootCase715BlockerBinding.Batch179
import Sixpack.EndpointRootCase715BlockerBinding.Batch180
import Sixpack.EndpointRootCase715BlockerBinding.Batch181
import Sixpack.EndpointRootCase715BlockerBinding.Batch182
import Sixpack.EndpointRootCase715BlockerBinding.Batch183
import Sixpack.EndpointRootCase715BlockerBinding.Batch184
import Sixpack.EndpointRootCase715BlockerBinding.Batch185
import Sixpack.EndpointRootCase715BlockerBinding.Batch186
import Sixpack.EndpointRootCase715BlockerBinding.Batch187
import Sixpack.EndpointRootCase715BlockerBinding.Batch188
import Sixpack.EndpointRootCase715BlockerBinding.Batch189
import Sixpack.EndpointRootCase715BlockerBinding.Batch190
import Sixpack.EndpointRootCase715BlockerBinding.Batch191
import Sixpack.EndpointRootCase715BlockerBinding.Batch192
import Sixpack.EndpointRootCase715BlockerBinding.Batch193
import Sixpack.EndpointRootCase715BlockerBinding.Batch194
import Sixpack.EndpointRootCase715BlockerBinding.Batch195
import Sixpack.EndpointRootCase715BlockerBinding.Batch196
import Sixpack.EndpointRootCase715BlockerBinding.Batch197
import Sixpack.EndpointRootCase715BlockerBinding.Batch198
import Sixpack.EndpointRootCase715BlockerBinding.Batch199
import Sixpack.EndpointRootCase715BlockerBinding.Batch200
import Sixpack.EndpointRootCase715BlockerBinding.Batch201
import Sixpack.EndpointRootCase715BlockerBinding.Batch202
import Sixpack.EndpointRootCase715BlockerBinding.Batch203
import Sixpack.EndpointRootCase715BlockerBinding.Batch204
import Sixpack.EndpointRootCase715BlockerBinding.Batch205
import Sixpack.EndpointRootCase715BlockerBinding.Batch206
import Sixpack.EndpointRootCase715BlockerBinding.Batch207
import Sixpack.EndpointRootCase715BlockerBinding.Batch208
import Sixpack.EndpointRootCase715BlockerBinding.Batch209
import Sixpack.EndpointRootCase715BlockerBinding.Batch210
import Sixpack.EndpointRootCase715BlockerBinding.Batch211
import Sixpack.EndpointRootCase715BlockerBinding.Batch212
import Sixpack.EndpointRootCase715BlockerBinding.Batch213
import Sixpack.EndpointRootCase715BlockerBinding.Batch214
import Sixpack.EndpointRootCase715BlockerBinding.Batch215
import Sixpack.EndpointRootCase715BlockerBinding.Batch216
import Sixpack.EndpointRootCase715BlockerBinding.Batch217
import Sixpack.EndpointRootCase715BlockerBinding.Batch218
import Sixpack.EndpointRootCase715BlockerBinding.Batch219
import Sixpack.EndpointRootCase715BlockerBinding.Batch220
import Sixpack.EndpointRootCase715BlockerBinding.Batch221
import Sixpack.EndpointRootCase715BlockerBinding.Batch222
import Sixpack.EndpointRootCase715BlockerBinding.Batch223
import Sixpack.EndpointRootCase715BlockerBinding.Batch224
import Sixpack.EndpointRootCase715BlockerBinding.Batch225
import Sixpack.EndpointRootCase715BlockerBinding.Batch226
import Sixpack.EndpointRootCase715BlockerBinding.Batch227
import Sixpack.EndpointRootCase715BlockerBinding.Batch228
import Sixpack.EndpointRootCase715BlockerBinding.Batch229
import Sixpack.EndpointRootCase715BlockerBinding.Batch230
import Sixpack.EndpointRootCase715BlockerBinding.Batch231
import Sixpack.EndpointRootCase715BlockerBinding.Batch232
import Sixpack.EndpointRootCase715BlockerBinding.Batch233
import Sixpack.EndpointRootCase715BlockerBinding.Batch234
import Sixpack.EndpointRootCase715BlockerBinding.Batch235
import Sixpack.EndpointRootCase715BlockerBinding.Batch236
import Sixpack.EndpointRootCase715BlockerBinding.Batch237
import Sixpack.EndpointRootCase715BlockerBinding.Batch238
import Sixpack.EndpointRootCase715BlockerBinding.Batch239
import Sixpack.EndpointRootCase715BlockerBinding.Batch240
import Sixpack.EndpointRootCase715BlockerBinding.Batch241
import Sixpack.EndpointRootCase715BlockerBinding.Batch242
import Sixpack.EndpointRootCase715BlockerBinding.Batch243
import Sixpack.EndpointRootCase715BlockerBinding.Batch244
import Sixpack.EndpointRootCase715BlockerBinding.Batch245
import Sixpack.EndpointRootCase715BlockerBinding.Batch246
import Sixpack.EndpointRootCase715BlockerBinding.Batch247
import Sixpack.EndpointRootCase715BlockerBinding.Batch248
import Sixpack.EndpointRootCase715BlockerBinding.Batch249
import Sixpack.EndpointRootCase715BlockerBinding.Batch250
import Sixpack.EndpointRootCase715BlockerBinding.Batch251
import Sixpack.EndpointRootCase715BlockerBinding.Batch252
import Sixpack.EndpointRootCase715BlockerBinding.Batch253
import Sixpack.EndpointRootCase715BlockerBinding.Batch254
import Sixpack.EndpointRootCase715BlockerBinding.Batch255
import Sixpack.EndpointRootCase715BlockerBinding.Batch256
import Sixpack.EndpointRootCase715BlockerBinding.Batch257
import Sixpack.EndpointRootCase715BlockerBinding.Batch258
import Sixpack.EndpointRootCase715BlockerBinding.Batch259
import Sixpack.EndpointRootCase715BlockerBinding.Batch260
import Sixpack.EndpointRootCase715BlockerBinding.Batch261
import Sixpack.EndpointRootCase715BlockerBinding.Batch262
import Sixpack.EndpointRootCase715BlockerBinding.Batch263
import Sixpack.EndpointRootCase715BlockerBinding.Batch264
import Sixpack.EndpointRootCase715BlockerBinding.Batch265
import Sixpack.EndpointRootCase715BlockerBinding.Batch266
import Sixpack.EndpointRootCase715BlockerBinding.Batch267
import Sixpack.EndpointRootCase715BlockerBinding.Batch268
import Sixpack.EndpointRootCase715BlockerBinding.Batch269
import Sixpack.EndpointRootCase715BlockerBinding.Batch270

set_option maxHeartbeats 20000000
set_option maxRecDepth 100000

namespace Sixpack

private theorem root_case715_initial_blocker_binding_batches (batch : Fin 271) (offset : Fin 128) :
    endpointRootDeclaredCoarseGroup (rootCase715BindingNode batch offset) = 2 →
    rootCase715RowGroup0Blockers (rootCase715InitialBlockerPosition (rootCase715BindingNode batch offset)) =
      rootCase715BindingNode batch offset := by
  fin_cases batch
  · exact root_case715_initial_blocker_binding_batch0 offset
  · exact root_case715_initial_blocker_binding_batch1 offset
  · exact root_case715_initial_blocker_binding_batch2 offset
  · exact root_case715_initial_blocker_binding_batch3 offset
  · exact root_case715_initial_blocker_binding_batch4 offset
  · exact root_case715_initial_blocker_binding_batch5 offset
  · exact root_case715_initial_blocker_binding_batch6 offset
  · exact root_case715_initial_blocker_binding_batch7 offset
  · exact root_case715_initial_blocker_binding_batch8 offset
  · exact root_case715_initial_blocker_binding_batch9 offset
  · exact root_case715_initial_blocker_binding_batch10 offset
  · exact root_case715_initial_blocker_binding_batch11 offset
  · exact root_case715_initial_blocker_binding_batch12 offset
  · exact root_case715_initial_blocker_binding_batch13 offset
  · exact root_case715_initial_blocker_binding_batch14 offset
  · exact root_case715_initial_blocker_binding_batch15 offset
  · exact root_case715_initial_blocker_binding_batch16 offset
  · exact root_case715_initial_blocker_binding_batch17 offset
  · exact root_case715_initial_blocker_binding_batch18 offset
  · exact root_case715_initial_blocker_binding_batch19 offset
  · exact root_case715_initial_blocker_binding_batch20 offset
  · exact root_case715_initial_blocker_binding_batch21 offset
  · exact root_case715_initial_blocker_binding_batch22 offset
  · exact root_case715_initial_blocker_binding_batch23 offset
  · exact root_case715_initial_blocker_binding_batch24 offset
  · exact root_case715_initial_blocker_binding_batch25 offset
  · exact root_case715_initial_blocker_binding_batch26 offset
  · exact root_case715_initial_blocker_binding_batch27 offset
  · exact root_case715_initial_blocker_binding_batch28 offset
  · exact root_case715_initial_blocker_binding_batch29 offset
  · exact root_case715_initial_blocker_binding_batch30 offset
  · exact root_case715_initial_blocker_binding_batch31 offset
  · exact root_case715_initial_blocker_binding_batch32 offset
  · exact root_case715_initial_blocker_binding_batch33 offset
  · exact root_case715_initial_blocker_binding_batch34 offset
  · exact root_case715_initial_blocker_binding_batch35 offset
  · exact root_case715_initial_blocker_binding_batch36 offset
  · exact root_case715_initial_blocker_binding_batch37 offset
  · exact root_case715_initial_blocker_binding_batch38 offset
  · exact root_case715_initial_blocker_binding_batch39 offset
  · exact root_case715_initial_blocker_binding_batch40 offset
  · exact root_case715_initial_blocker_binding_batch41 offset
  · exact root_case715_initial_blocker_binding_batch42 offset
  · exact root_case715_initial_blocker_binding_batch43 offset
  · exact root_case715_initial_blocker_binding_batch44 offset
  · exact root_case715_initial_blocker_binding_batch45 offset
  · exact root_case715_initial_blocker_binding_batch46 offset
  · exact root_case715_initial_blocker_binding_batch47 offset
  · exact root_case715_initial_blocker_binding_batch48 offset
  · exact root_case715_initial_blocker_binding_batch49 offset
  · exact root_case715_initial_blocker_binding_batch50 offset
  · exact root_case715_initial_blocker_binding_batch51 offset
  · exact root_case715_initial_blocker_binding_batch52 offset
  · exact root_case715_initial_blocker_binding_batch53 offset
  · exact root_case715_initial_blocker_binding_batch54 offset
  · exact root_case715_initial_blocker_binding_batch55 offset
  · exact root_case715_initial_blocker_binding_batch56 offset
  · exact root_case715_initial_blocker_binding_batch57 offset
  · exact root_case715_initial_blocker_binding_batch58 offset
  · exact root_case715_initial_blocker_binding_batch59 offset
  · exact root_case715_initial_blocker_binding_batch60 offset
  · exact root_case715_initial_blocker_binding_batch61 offset
  · exact root_case715_initial_blocker_binding_batch62 offset
  · exact root_case715_initial_blocker_binding_batch63 offset
  · exact root_case715_initial_blocker_binding_batch64 offset
  · exact root_case715_initial_blocker_binding_batch65 offset
  · exact root_case715_initial_blocker_binding_batch66 offset
  · exact root_case715_initial_blocker_binding_batch67 offset
  · exact root_case715_initial_blocker_binding_batch68 offset
  · exact root_case715_initial_blocker_binding_batch69 offset
  · exact root_case715_initial_blocker_binding_batch70 offset
  · exact root_case715_initial_blocker_binding_batch71 offset
  · exact root_case715_initial_blocker_binding_batch72 offset
  · exact root_case715_initial_blocker_binding_batch73 offset
  · exact root_case715_initial_blocker_binding_batch74 offset
  · exact root_case715_initial_blocker_binding_batch75 offset
  · exact root_case715_initial_blocker_binding_batch76 offset
  · exact root_case715_initial_blocker_binding_batch77 offset
  · exact root_case715_initial_blocker_binding_batch78 offset
  · exact root_case715_initial_blocker_binding_batch79 offset
  · exact root_case715_initial_blocker_binding_batch80 offset
  · exact root_case715_initial_blocker_binding_batch81 offset
  · exact root_case715_initial_blocker_binding_batch82 offset
  · exact root_case715_initial_blocker_binding_batch83 offset
  · exact root_case715_initial_blocker_binding_batch84 offset
  · exact root_case715_initial_blocker_binding_batch85 offset
  · exact root_case715_initial_blocker_binding_batch86 offset
  · exact root_case715_initial_blocker_binding_batch87 offset
  · exact root_case715_initial_blocker_binding_batch88 offset
  · exact root_case715_initial_blocker_binding_batch89 offset
  · exact root_case715_initial_blocker_binding_batch90 offset
  · exact root_case715_initial_blocker_binding_batch91 offset
  · exact root_case715_initial_blocker_binding_batch92 offset
  · exact root_case715_initial_blocker_binding_batch93 offset
  · exact root_case715_initial_blocker_binding_batch94 offset
  · exact root_case715_initial_blocker_binding_batch95 offset
  · exact root_case715_initial_blocker_binding_batch96 offset
  · exact root_case715_initial_blocker_binding_batch97 offset
  · exact root_case715_initial_blocker_binding_batch98 offset
  · exact root_case715_initial_blocker_binding_batch99 offset
  · exact root_case715_initial_blocker_binding_batch100 offset
  · exact root_case715_initial_blocker_binding_batch101 offset
  · exact root_case715_initial_blocker_binding_batch102 offset
  · exact root_case715_initial_blocker_binding_batch103 offset
  · exact root_case715_initial_blocker_binding_batch104 offset
  · exact root_case715_initial_blocker_binding_batch105 offset
  · exact root_case715_initial_blocker_binding_batch106 offset
  · exact root_case715_initial_blocker_binding_batch107 offset
  · exact root_case715_initial_blocker_binding_batch108 offset
  · exact root_case715_initial_blocker_binding_batch109 offset
  · exact root_case715_initial_blocker_binding_batch110 offset
  · exact root_case715_initial_blocker_binding_batch111 offset
  · exact root_case715_initial_blocker_binding_batch112 offset
  · exact root_case715_initial_blocker_binding_batch113 offset
  · exact root_case715_initial_blocker_binding_batch114 offset
  · exact root_case715_initial_blocker_binding_batch115 offset
  · exact root_case715_initial_blocker_binding_batch116 offset
  · exact root_case715_initial_blocker_binding_batch117 offset
  · exact root_case715_initial_blocker_binding_batch118 offset
  · exact root_case715_initial_blocker_binding_batch119 offset
  · exact root_case715_initial_blocker_binding_batch120 offset
  · exact root_case715_initial_blocker_binding_batch121 offset
  · exact root_case715_initial_blocker_binding_batch122 offset
  · exact root_case715_initial_blocker_binding_batch123 offset
  · exact root_case715_initial_blocker_binding_batch124 offset
  · exact root_case715_initial_blocker_binding_batch125 offset
  · exact root_case715_initial_blocker_binding_batch126 offset
  · exact root_case715_initial_blocker_binding_batch127 offset
  · exact root_case715_initial_blocker_binding_batch128 offset
  · exact root_case715_initial_blocker_binding_batch129 offset
  · exact root_case715_initial_blocker_binding_batch130 offset
  · exact root_case715_initial_blocker_binding_batch131 offset
  · exact root_case715_initial_blocker_binding_batch132 offset
  · exact root_case715_initial_blocker_binding_batch133 offset
  · exact root_case715_initial_blocker_binding_batch134 offset
  · exact root_case715_initial_blocker_binding_batch135 offset
  · exact root_case715_initial_blocker_binding_batch136 offset
  · exact root_case715_initial_blocker_binding_batch137 offset
  · exact root_case715_initial_blocker_binding_batch138 offset
  · exact root_case715_initial_blocker_binding_batch139 offset
  · exact root_case715_initial_blocker_binding_batch140 offset
  · exact root_case715_initial_blocker_binding_batch141 offset
  · exact root_case715_initial_blocker_binding_batch142 offset
  · exact root_case715_initial_blocker_binding_batch143 offset
  · exact root_case715_initial_blocker_binding_batch144 offset
  · exact root_case715_initial_blocker_binding_batch145 offset
  · exact root_case715_initial_blocker_binding_batch146 offset
  · exact root_case715_initial_blocker_binding_batch147 offset
  · exact root_case715_initial_blocker_binding_batch148 offset
  · exact root_case715_initial_blocker_binding_batch149 offset
  · exact root_case715_initial_blocker_binding_batch150 offset
  · exact root_case715_initial_blocker_binding_batch151 offset
  · exact root_case715_initial_blocker_binding_batch152 offset
  · exact root_case715_initial_blocker_binding_batch153 offset
  · exact root_case715_initial_blocker_binding_batch154 offset
  · exact root_case715_initial_blocker_binding_batch155 offset
  · exact root_case715_initial_blocker_binding_batch156 offset
  · exact root_case715_initial_blocker_binding_batch157 offset
  · exact root_case715_initial_blocker_binding_batch158 offset
  · exact root_case715_initial_blocker_binding_batch159 offset
  · exact root_case715_initial_blocker_binding_batch160 offset
  · exact root_case715_initial_blocker_binding_batch161 offset
  · exact root_case715_initial_blocker_binding_batch162 offset
  · exact root_case715_initial_blocker_binding_batch163 offset
  · exact root_case715_initial_blocker_binding_batch164 offset
  · exact root_case715_initial_blocker_binding_batch165 offset
  · exact root_case715_initial_blocker_binding_batch166 offset
  · exact root_case715_initial_blocker_binding_batch167 offset
  · exact root_case715_initial_blocker_binding_batch168 offset
  · exact root_case715_initial_blocker_binding_batch169 offset
  · exact root_case715_initial_blocker_binding_batch170 offset
  · exact root_case715_initial_blocker_binding_batch171 offset
  · exact root_case715_initial_blocker_binding_batch172 offset
  · exact root_case715_initial_blocker_binding_batch173 offset
  · exact root_case715_initial_blocker_binding_batch174 offset
  · exact root_case715_initial_blocker_binding_batch175 offset
  · exact root_case715_initial_blocker_binding_batch176 offset
  · exact root_case715_initial_blocker_binding_batch177 offset
  · exact root_case715_initial_blocker_binding_batch178 offset
  · exact root_case715_initial_blocker_binding_batch179 offset
  · exact root_case715_initial_blocker_binding_batch180 offset
  · exact root_case715_initial_blocker_binding_batch181 offset
  · exact root_case715_initial_blocker_binding_batch182 offset
  · exact root_case715_initial_blocker_binding_batch183 offset
  · exact root_case715_initial_blocker_binding_batch184 offset
  · exact root_case715_initial_blocker_binding_batch185 offset
  · exact root_case715_initial_blocker_binding_batch186 offset
  · exact root_case715_initial_blocker_binding_batch187 offset
  · exact root_case715_initial_blocker_binding_batch188 offset
  · exact root_case715_initial_blocker_binding_batch189 offset
  · exact root_case715_initial_blocker_binding_batch190 offset
  · exact root_case715_initial_blocker_binding_batch191 offset
  · exact root_case715_initial_blocker_binding_batch192 offset
  · exact root_case715_initial_blocker_binding_batch193 offset
  · exact root_case715_initial_blocker_binding_batch194 offset
  · exact root_case715_initial_blocker_binding_batch195 offset
  · exact root_case715_initial_blocker_binding_batch196 offset
  · exact root_case715_initial_blocker_binding_batch197 offset
  · exact root_case715_initial_blocker_binding_batch198 offset
  · exact root_case715_initial_blocker_binding_batch199 offset
  · exact root_case715_initial_blocker_binding_batch200 offset
  · exact root_case715_initial_blocker_binding_batch201 offset
  · exact root_case715_initial_blocker_binding_batch202 offset
  · exact root_case715_initial_blocker_binding_batch203 offset
  · exact root_case715_initial_blocker_binding_batch204 offset
  · exact root_case715_initial_blocker_binding_batch205 offset
  · exact root_case715_initial_blocker_binding_batch206 offset
  · exact root_case715_initial_blocker_binding_batch207 offset
  · exact root_case715_initial_blocker_binding_batch208 offset
  · exact root_case715_initial_blocker_binding_batch209 offset
  · exact root_case715_initial_blocker_binding_batch210 offset
  · exact root_case715_initial_blocker_binding_batch211 offset
  · exact root_case715_initial_blocker_binding_batch212 offset
  · exact root_case715_initial_blocker_binding_batch213 offset
  · exact root_case715_initial_blocker_binding_batch214 offset
  · exact root_case715_initial_blocker_binding_batch215 offset
  · exact root_case715_initial_blocker_binding_batch216 offset
  · exact root_case715_initial_blocker_binding_batch217 offset
  · exact root_case715_initial_blocker_binding_batch218 offset
  · exact root_case715_initial_blocker_binding_batch219 offset
  · exact root_case715_initial_blocker_binding_batch220 offset
  · exact root_case715_initial_blocker_binding_batch221 offset
  · exact root_case715_initial_blocker_binding_batch222 offset
  · exact root_case715_initial_blocker_binding_batch223 offset
  · exact root_case715_initial_blocker_binding_batch224 offset
  · exact root_case715_initial_blocker_binding_batch225 offset
  · exact root_case715_initial_blocker_binding_batch226 offset
  · exact root_case715_initial_blocker_binding_batch227 offset
  · exact root_case715_initial_blocker_binding_batch228 offset
  · exact root_case715_initial_blocker_binding_batch229 offset
  · exact root_case715_initial_blocker_binding_batch230 offset
  · exact root_case715_initial_blocker_binding_batch231 offset
  · exact root_case715_initial_blocker_binding_batch232 offset
  · exact root_case715_initial_blocker_binding_batch233 offset
  · exact root_case715_initial_blocker_binding_batch234 offset
  · exact root_case715_initial_blocker_binding_batch235 offset
  · exact root_case715_initial_blocker_binding_batch236 offset
  · exact root_case715_initial_blocker_binding_batch237 offset
  · exact root_case715_initial_blocker_binding_batch238 offset
  · exact root_case715_initial_blocker_binding_batch239 offset
  · exact root_case715_initial_blocker_binding_batch240 offset
  · exact root_case715_initial_blocker_binding_batch241 offset
  · exact root_case715_initial_blocker_binding_batch242 offset
  · exact root_case715_initial_blocker_binding_batch243 offset
  · exact root_case715_initial_blocker_binding_batch244 offset
  · exact root_case715_initial_blocker_binding_batch245 offset
  · exact root_case715_initial_blocker_binding_batch246 offset
  · exact root_case715_initial_blocker_binding_batch247 offset
  · exact root_case715_initial_blocker_binding_batch248 offset
  · exact root_case715_initial_blocker_binding_batch249 offset
  · exact root_case715_initial_blocker_binding_batch250 offset
  · exact root_case715_initial_blocker_binding_batch251 offset
  · exact root_case715_initial_blocker_binding_batch252 offset
  · exact root_case715_initial_blocker_binding_batch253 offset
  · exact root_case715_initial_blocker_binding_batch254 offset
  · exact root_case715_initial_blocker_binding_batch255 offset
  · exact root_case715_initial_blocker_binding_batch256 offset
  · exact root_case715_initial_blocker_binding_batch257 offset
  · exact root_case715_initial_blocker_binding_batch258 offset
  · exact root_case715_initial_blocker_binding_batch259 offset
  · exact root_case715_initial_blocker_binding_batch260 offset
  · exact root_case715_initial_blocker_binding_batch261 offset
  · exact root_case715_initial_blocker_binding_batch262 offset
  · exact root_case715_initial_blocker_binding_batch263 offset
  · exact root_case715_initial_blocker_binding_batch264 offset
  · exact root_case715_initial_blocker_binding_batch265 offset
  · exact root_case715_initial_blocker_binding_batch266 offset
  · exact root_case715_initial_blocker_binding_batch267 offset
  · exact root_case715_initial_blocker_binding_batch268 offset
  · exact root_case715_initial_blocker_binding_batch269 offset
  · exact root_case715_initial_blocker_binding_batch270 offset

theorem root_case715_initial_blocker_covered (node : Fin 34660)
    (hgroup : endpointRootDeclaredCoarseGroup node = 2) :
    node ∈ Finset.univ.image rootCase715RowGroup0Blockers := by
  let batch : Fin 271 := ⟨node.val/128,by have h := node.isLt; omega⟩
  let offset : Fin 128 := ⟨node.val%128,Nat.mod_lt _ (by decide)⟩
  have hi : rootCase715BindingNode batch offset = node := by
    apply Fin.ext
    change (128*(node.val/128)+node.val%128)%34660 = node.val
    rw [Nat.div_add_mod,Nat.mod_eq_of_lt node.isLt]
  have h := root_case715_initial_blocker_binding_batches batch offset
  rw [hi] at h
  exact Finset.mem_image.mpr ⟨rootCase715InitialBlockerPosition node,Finset.mem_univ _,h hgroup⟩

end Sixpack
